# Generated by Django 5.2.2 on 2025-07-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0002_alter_department_code'),
    ]

    operations = [
    ]
