# Generated by Django 5.2.2 on 2025-07-08 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_auto_20250708_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('stocktake_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.stocktaketable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stocktake_table')},
            },
        ),
    ]
