# Generated by Django 5.2.2 on 2025-07-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0004_stocktakeaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocktakeaccess',
            unique_together={('user', 'stocktake_table')},
        ),
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(default='fa-building', max_length=30),
        ),
        migrations.AddField(
            model_name='stocktakeaccess',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='stocktakeaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeaccess',
            unique_together={('session_key', 'stocktake_table'), ('user', 'stocktake_table')},
        ),
    ]
